# Generated by Django 5.0 on 2023-12-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
